os: linux
language: node_js
services:
  - docker

before_install:
  - docker build -t antoniuk02/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true antoniuk02/react-test npm test 

after_success:
  - docker build -t antoniuk02/multi-client ./client ./client
  - docker build -t antoniuk02/multi-server ./server ./server
  - docker build -t antoniuk02/multi-worker ./worker ./worker
  - docker build -t antoniuk02/multi-nginx ./nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push antoniuk02/multi-client
  - docker push antoniuk02/multi-server
  - docker push antoniuk02/multi-nginx
  - docker push antoniuk02/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-2-991075679647
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

