sudo: required
services:
  - docker


before_install:
  - docker build -t antoniuk02/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true antoniuk02/react-test npm test 

after_success:
  - docker build -t antoniuk02/multi-client ./client .
  - docker build -t antoniuk02/multi-server ./server .
  - docker build -t antoniuk02/multi-worker ./worker .
  - docker build -t antoniuk02/multi-nginx ./nginx .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push antoniuk02/multi-client
  - docker push antoniuk02/multi-server
  - docker push antoniuk02/multi-nginx
  - docker push antoniuk02/multi-worker



